INSERT INTO products (slug, name, brand, size_ml, fragrance_type, price_clp, gender, description, notes_top, notes_heart, notes_base, image_url, image_fallback, featured, sort_order) VALUES
('ck-one-shock', 'CK One Shock For Her', 'Calvin Klein', 100, 'EDT', 44990, 'female', 'Audaz y seductora. La primera fragancia femenina de la familia CK One rompe las reglas con un corazón de chocolate y notas orientales especiadas. Sexy e irresistible.', 'Flor de pasionaria, amapola roja, peonía', 'Jazmín, narciso, chocolate mexicano, zarzamora', 'Almizcle, pachulí, ámbar, vainilla', 'https://img.fragrancenet.com/perfumes/CalvinKlein/CalvinKleinCKOneShockHer/CalvinKleinCKOneShockHer_L.jpg', 'https://www.perfumedirect.com/cdn/shop/products/ck-one-shock-her-100ml_800x.jpg', true, 1),

('stronger-with-you', 'Stronger With You', 'Emporio Armani', 50, 'EDT', 69990, 'male', 'Para el hombre que conecta de verdad. Una fragancia especiada y dulce que combina frescura mediterránea con calidez envolvente. Elegante, moderno y memorable.', 'Cardamomo, hojas de violeta', 'Lavanda, salvia, castaña glaseada', 'Vainilla, cedro, almizcle', 'https://img.fragrancenet.com/perfumes/GiorgioArmani/EmporioArmaniStrongerWithYou/EmporioArmaniStrongerWithYou_L.jpg', 'https://www.sephora.com/productimages/sku/s2246563-main-zoom.jpg', true, 2),

('toy2-bubblegum', 'Toy 2 Bubble Gum', 'Moschino', 100, 'EDT', 64990, 'female', 'Divertida, juvenil y totalmente adictiva. El icónico osito rosa de Moschino en un aroma dulce y frutal que captura la alegría y la energía de vivir sin reglas.', 'Frutas confitadas, naranja amarga, limón', 'Goma de mascar, rosa búlgara, durazno, jengibre', 'Almizcle, ambroxan, cedro', 'https://img.fragrancenet.com/perfumes/Moschino/MoschinoToy2BubbleGum/MoschinoToy2BubbleGum_L.jpg', 'https://images.thefragranceshop.co.uk/catalog/product/m/o/moschino-toy-2-bubblegum-edt-100ml_1.jpg', false, 3),

('light-blue-dg', 'Light Blue', 'Dolce & Gabbana', 100, 'EDT', 69990, 'female', 'El Mediterráneo en un frasco. Fresca, luminosa e icónica. Light Blue evoca las tardes de verano junto al mar con su frescura cítrica y su corazón floral atemporal.', 'Limón siciliano, manzana Granny Smith, cedro', 'Bambú, jazmín, rosa blanca', 'Cedro, almizcle, ámbar', 'https://img.fragrancenet.com/perfumes/DolceGabbana/DolceGabbanaDolceGabbanaLightBlue/DolceGabbanaDolceGabbanaLightBlue_L.jpg', 'https://www.sephora.com/productimages/sku/s1891629-main-zoom.jpg', true, 4),

('yes-i-am', 'Yes I Am', 'Cacharel', 50, 'EDP', 39990, 'female', 'Una declaración de amor propio. Floral intensa con corazón de rosas excepcionales y una base cálida de cachemira. Sofisticada, femenina y poderosa.', 'Pera, pera glaseada', 'Rosa centifolia, rosa turca, iris', 'Almizcle, madera de cachemira, sándalo', 'https://img.fragrancenet.com/perfumes/Cacharel/CacharelYesIAm/CacharelYesIAm_L.jpg', 'https://images.thefragranceshop.co.uk/catalog/product/y/e/yes-i-am-cacharel-edp-50ml.jpg', false, 5),

('mandarin-sky-elixir', 'Odyssey Mandarin Sky Elixir', 'Armaf', 100, 'EDP', 54990, 'unisex', 'Edición limitada 2025. Oriental amaderada unisex de larga duración excepcional. Mandarina vibrante que evoluciona hacia un corazón especiado y una base cálida de vainilla.', 'Mandarina, naranja, lavanda, pimienta negra, cardamomo', 'Caramelo, haba tonka, pachulí, incienso', 'Vainilla, vetiver', 'https://img.fragrancenet.com/perfumes/Armaf/ArmafOdysseyMandarinSkyElixir/ArmafOdysseyMandarinSkyElixir_L.jpg', 'https://www.eliteperfumes.cl/cdn/shop/files/ODYSSEY-MANDARIN-SKY-ELIXIR-EDP-100ML.jpg', true, 6);
