-- Coast Parfum — Seed Data
-- Run after 001_initial.sql

INSERT INTO products (slug, name, brand, size_ml, fragrance_type, price_clp, gender, description, notes_top, notes_heart, notes_base, gradient_class, accent_color, featured, limited, sort_order) VALUES
(
  'ck-one-shock',
  'CK One Shock For Her',
  'Calvin Klein',
  100,
  'EDT',
  44990,
  'female',
  'Audaz y seductora. La primera fragancia femenina de la familia CK One rompe las reglas con un corazón de chocolate y notas orientales especiadas. Sexy e irresistible.',
  'Flor de pasionaria, amapola roja, peonía',
  'Jazmín, narciso, chocolate mexicano, zarzamora',
  'Almizcle, pachulí, ámbar, vainilla',
  'from-rose-950 via-stone-900 to-[#0F0800]',
  '#E8A0B0',
  true,
  false,
  1
),
(
  'stronger-with-you',
  'Stronger With You',
  'Emporio Armani',
  50,
  'EDT',
  69990,
  'male',
  'Para el hombre que conecta de verdad. Una fragancia especiada y dulce que combina frescura mediterránea con calidez envolvente. Elegante, moderno y memorable.',
  'Cardamomo, hojas de violeta',
  'Lavanda, salvia, castaña glaseada',
  'Vainilla, cedro, almizcle',
  'from-stone-950 via-zinc-900 to-[#080808]',
  '#8B9DC3',
  true,
  false,
  2
),
(
  'toy2-bubblegum',
  'Toy 2 Bubble Gum',
  'Moschino',
  100,
  'EDT',
  64990,
  'female',
  'Divertida, juvenil y totalmente adictiva. El icónico osito rosa de Moschino en un aroma dulce y frutal que captura la alegría y la energía de vivir sin reglas.',
  'Frutas confitadas, naranja amarga, limón',
  'Goma de mascar, rosa búlgara, durazno, jengibre',
  'Almizcle, ambroxan, cedro',
  'from-pink-950 via-fuchsia-950 to-[#0F0808]',
  '#F472B6',
  false,
  false,
  3
),
(
  'light-blue-dg',
  'Light Blue',
  'Dolce & Gabbana',
  100,
  'EDT',
  69990,
  'female',
  'El Mediterráneo en un frasco. Fresca, luminosa e icónica. Light Blue evoca las tardes de verano junto al mar con su frescura cítrica y su corazón floral atemporal.',
  'Limón siciliano, manzana Granny Smith, cedro',
  'Bambú, jazmín, rosa blanca',
  'Cedro, almizcle, ámbar',
  'from-sky-950 via-blue-950 to-[#050A0F]',
  '#7DD3FC',
  true,
  false,
  4
),
(
  'yes-i-am',
  'Yes I Am',
  'Cacharel',
  50,
  'EDP',
  39990,
  'female',
  'Una declaración de amor propio. Floral intensa con corazón de rosas excepcionales y una base cálida de cachemira. Sofisticada, femenina y poderosa.',
  'Pera, pera glaseada',
  'Rosa centifolia, rosa turca, iris',
  'Almizcle, madera de cachemira, sándalo',
  'from-red-950 via-rose-950 to-[#0F0505]',
  '#FB7185',
  false,
  false,
  5
),
(
  'mandarin-sky-elixir',
  'Odyssey Mandarin Sky Elixir',
  'Armaf',
  100,
  'EDP',
  54990,
  'unisex',
  'Edición limitada 2025. Oriental amaderada unisex de larga duración excepcional. Mandarina vibrante que evoluciona hacia un corazón especiado y una base cálida de vainilla.',
  'Mandarina, naranja, lavanda, pimienta negra, cardamomo',
  'Caramelo, haba tonka, pachulí, incienso',
  'Vainilla, vetiver',
  'from-blue-950 via-indigo-950 to-[#050508]',
  '#818CF8',
  true,
  true,
  6
);
